CREATE TABLE proteinGroups (
    protein_id                     VARCHAR (50) UNIQUE  DEFAULT (0),
    protein_major_id               VARCHAR (50) UNIQUE DEFAULT (0),
    peptide_count                  VARCHAR (10) DEFAULT (0),
    peptide_count_razor_unique     VARCHAR (10) DEFAULT (0),
    peptide_count_unique           VARCHAR (10) DEFAULT (0),
    protein_names                  TEXT (300) DEFAULT (0),
    gene_names                     VARCHAR (50) DEFAULT (0),
    fasta_headers                  TEXT (1000) DEFAULT (0),
    number_of_proteins             INT           DEFAULT (0),
    peptides                       INT           DEFAULT (0),
    razor_unique_peptides          INT           DEFAULT (0),
    unique_peptides                INT           DEFAULT (0),
    peptides_aa3672                INT           DEFAULT (0),
    peptides_aa3710                INT           DEFAULT (0),
    peptides_aa3715                INT           DEFAULT (0),
    peptides_aa3864                INT           DEFAULT (0),
    peptides_aaa00j                INT           DEFAULT (0),
    peptides_aaa00n                INT           DEFAULT (0),
    peptides_aaa010                INT           DEFAULT (0),
    peptides_aaa01r                INT           DEFAULT (0),
    peptides_aaa022                INT           DEFAULT (0),
    peptides_aga002                INT           DEFAULT (0),
    peptides_aga02n                INT           DEFAULT (0),
    razor_unique_peptides_aa3672   INT           DEFAULT (0),
    razor_unique_peptides_aa3710   INT           DEFAULT (0),
    razor_unique_peptides_aa3715   INT           DEFAULT (0),
    razor_unique_peptides_aa3864   INT           DEFAULT (0),
    razor_unique_peptides_aaa00j   INT           DEFAULT (0),
    razor_unique_peptides_aaa00n   INT           DEFAULT (0),
    razor_unique_peptides_aaa010   INT           DEFAULT (0),
    razor_unique_peptides_aaa01r   INT           DEFAULT (0),
    razor_unique_peptides_aaa022   INT           DEFAULT (0),
    razor_unique_peptides_aga002   INT           DEFAULT (0),
    razor_unique_peptides_aga02n   INT           DEFAULT (0),
    unique_peptides_aa3672         INT           DEFAULT (0),
    unique_peptides_aa3710         INT           DEFAULT (0),
    unique_peptides_aa3715         INT           DEFAULT (0),
    unique_peptides_aa3864         INT           DEFAULT (0),
    unique_peptides_aaa00j         INT           DEFAULT (0),
    unique_peptides_aaa00n         INT           DEFAULT (0),
    unique_peptides_aaa010         INT           DEFAULT (0),
    unique_peptides_aaa01r         INT           DEFAULT (0),
    unique_peptides_aaa022         INT           DEFAULT (0),
    unique_peptides_aga002         INT           DEFAULT (0),
    unique_peptides_aga02n         INT           DEFAULT (0),
    sequence_coverage              DECIMAL       DEFAULT (0),
    unique_razor_sequence_coverage DECIMAL       DEFAULT (0),
    unique_sequence_coverage       DECIMAL       DEFAULT (0),
    mol_weight                     DECIMAL       DEFAULT (0),
    sequence_length                INT           DEFAULT (0),
    sequence_lengths               VARCHAR (50)  DEFAULT (0),
    fraction_average               DECIMAL       DEFAULT (0),
    fraction_1                     DECIMAL       DEFAULT (0),
    qvalue                         DECIMAL       DEFAULT (0),
    score                          DECIMAL       DEFAULT (0),
    sequence_coverage_aa3672       DECIMAL       DEFAULT (0),
    sequence_coverage_aa3710       DECIMAL       DEFAULT (0),
    sequence_coverage_aa3715       DECIMAL       DEFAULT (0),
    sequence_coverage_aa3864       DECIMAL       DEFAULT (0),
    sequence_coverage_aaa00j       DECIMAL       DEFAULT (0),
    sequence_coverage_aaa00n       DECIMAL       DEFAULT (0),
    sequence_coverage_aaa010       DECIMAL       DEFAULT (0),
    sequence_coverage_aaa01r       DECIMAL       DEFAULT (0),
    sequence_coverage_aaa022       DECIMAL       DEFAULT (0),
    sequence_coverage_aga002       DECIMAL       DEFAULT (0),
    sequence_coverage_aga02n       DECIMAL       DEFAULT (0),
    intensity                      BIGINT        DEFAULT (0),
    intensity_aa3672               BIGINT        DEFAULT (0),
    intensity_aa3710               BIGINT        DEFAULT (0),
    intensity_aa3715               BIGINT        DEFAULT (0),
    intensity_aa3864               BIGINT        DEFAULT (0),
    intensity_aaa00j               BIGINT        DEFAULT (0),
    intensity_aaa00n               BIGINT        DEFAULT (0),
    intensity_aaa010               BIGINT        DEFAULT (0),
    intensity_aaa01r               BIGINT        DEFAULT (0),
    intensity_aaa022               BIGINT        DEFAULT (0),
    intensity_aga002               BIGINT        DEFAULT (0),
    intensity_aga02n               BIGINT        DEFAULT (0)
);
